services:
  # Update this to the name of the service you want to work with in your compose.yml file
  development:
    build:
      context: .
      dockerfile: Dockerfile.wp-plugin
      args:
        PHP_OLDEST_VERSION: ${PHP_OLDEST_VERSION:-7.4}
        PHP_LATEST_VERSION: ${PHP_LATEST_VERSION:-8.3}
    environment:
      # 開発環境で使用するPHP及びWordPressのバージョン
      # ※PHPのバージョンは上記Dockerイメージ作成時のバージョンのいずれかを指定すること
      - PHP_VERSION=${PHP_VERSION:-7.4} # PHPのバージョン(マイナーバージョンまで指定)
      - WP_VERSION=${WP_VERSION:-5.4} # WordPressのバージョン(https://ja.wordpress.org/download/releases/ に記載のタグ)
      - DATABASE_IMAGE=${DATABASE_IMAGE:-mariadb:lts} # データベースのDockerイメージ
      # Dockerネットワーク名
      # => WordPressとプライベートネットを接続できるようにする
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME:-dev_network}
    volumes:
      - ..:/workspaces
      # ./
      - node_modules:/workspaces/node_modules
      - pnpm_store:/workspaces/.pnpm-store
      # apps/wp-plugin
      - wp_plugin__intelephense:/workspaces/apps/wp-plugin/.intelephense
      - wp_plugin_includes_vendor:/workspaces/apps/wp-plugin/includes/vendor
      - wp_plugin_tests_vendor:/workspaces/apps/wp-plugin/tests/vendor
      - wp_plugin_node_modules:/workspaces/apps/wp-plugin/node_modules

    #   - ../../serendipity-resources/public:/workspaces/public
    #   - ../../serendipity-resources/i18n:/workspaces/i18n
    #   - ../../serendipity-resources/graphql/schema:/workspaces/includes/assets/graphql/schema

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules:
  pnpm_store:
  wp_plugin__intelephense:
  wp_plugin_includes_vendor:
  wp_plugin_tests_vendor:
  wp_plugin_node_modules:
