# 開発コンテナから起動するコンテナを定義
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.5.2
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - wpnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      VIRTUAL_HOST: "phpmyadmin.dev.localhost"
      VIRTUAL_PORT: "80"
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - wpnetwork

  mysql-phpunit-oldest:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wpnetwork

  mysql-phpunit-latest:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mysql-phpunit-not-support:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-oldest:
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-latest:
    image: mariadb:11.4.2
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-not-support:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  privatenet-1:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    environment:
      HARDHAT_CHAIN_ID: "31337"
      HARDHAT_PORT: "8545"
    ports:
      - "8545:8545"
    networks:
      - wpnetwork

  tests-privatenet-1:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    environment:
      HARDHAT_CHAIN_ID: "31337"
      HARDHAT_PORT: "8545"
    networks:
      - wpnetwork

  privatenet-2:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    environment:
      HARDHAT_CHAIN_ID: "31338"
      HARDHAT_PORT: "8546"
    ports:
      - "8546:8546"
    networks:
      - wpnetwork

  tests-privatenet-2:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    environment:
      HARDHAT_CHAIN_ID: "31338"
      HARDHAT_PORT: "8546"
    networks:
      - wpnetwork
