# 開発環境、CI共通で起動するコンテナを定義
services:
  mysql-phpunit-oldest:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mysql-phpunit-latest:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mysql-phpunit-not-support:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-oldest:
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-latest:
    image: mariadb:11.4.2
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  mariadb-phpunit-not-support:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork

  tests-privatenet-1:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: tests-privatenet-1.local
    environment:
      HARDHAT_CHAIN_ID: "31337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork

  tests-privatenet-2:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: tests-privatenet-2.local
    environment:
      HARDHAT_CHAIN_ID: "1337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork
