# 開発中のみ使用する1コンテナを定義
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.5.2
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - wpnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    environment:
      VIRTUAL_HOST: "phpmyadmin.local"
      VIRTUAL_PORT: "80"
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - wpnetwork

  privatenet-1:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: privatenet-1.local
    environment:
      VIRTUAL_HOST: "privatenet-1.local"
      VIRTUAL_PORT: "80"
      HARDHAT_CHAIN_ID: "31337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork

  privatenet-2:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: privatenet-2.local
    environment:
      VIRTUAL_HOST: "privatenet-2.local"
      VIRTUAL_PORT: "80"
      HARDHAT_CHAIN_ID: "1337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork

  wp-sandbox-latest:
    # バージョン変更時は他の箇所も変更が必要
    # @see .github/workflows/ci.yml
    image: wordpress:6.6.2
    depends_on:
      - wp-sandbox-db-latest
    ports:
      - "8887:80"
    environment:
      WORDPRESS_DB_HOST: wp-sandbox-db-latest
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpnetwork
    volumes:
      - wp-sandbox-latest:/var/www/html
      - ../..:/var/www/html/wp-content/plugins/workspaces
  wp-sandbox-db-latest:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    networks:
      - wpnetwork
    volumes:
      - wp-sandbox-db-latest:/var/lib/mysql

volumes:
  wp-sandbox-latest: {}
  wp-sandbox-db-latest: {}
