# 開発環境、CI共通で起動するコンテナを定義
services:
  tests-privatenet-1:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: tests-privatenet-1.local
    environment:
      HARDHAT_CHAIN_ID: "31337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork

  tests-privatenet-2:
    build:
      context: ./privatenet
      dockerfile: Dockerfile
    hostname: tests-privatenet-2.local
    environment:
      HARDHAT_CHAIN_ID: "1337"
      HARDHAT_PORT: "80"
    networks:
      - wpnetwork
