version: '3'
# 開発コンテナで起動するためのdocker-compose
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - "1000:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password

