# wp-envで起動される、いずれかのコンテナが立ち上がるまで待機し、そのコンテナ名に使用されているハッシュ値(ディレクトリ名)を取得する。
# ※ `[hash]_default`がネットワーク名になる。
loop_count=1800
for i in $(seq $loop_count); do
	# 起動中のコンテナ名に32桁のハッシュ値が含まれる場合は、そのハッシュ値を取得
	# ※ `docker network ls`では、wp-env起動前に取得できるパータンがあるため、`docker ps`を使用
	hash=$(docker ps | grep -oE '[0-9a-f]{32}')

	if [[ -n $hash ]]; then
		# ハッシュ値が取得できた場合はループを抜ける
		break
	elif [[ $i -eq $loop_count ]]; then
		# ループ回数が上限に達した場合はエラーを出力して終了
		echo "[F8E1A99C] Error: hash not found."
		exit 1
	fi

	# ハッシュ値が取得できない場合は1秒待機して再度取得を試みる
	echo "[2958FB68] Waiting for the hash value to be found. ($i/$loop_count)"
	sleep 1
done


# `compose.network.yml`ファイルを更新
docker_network_file_path=$(dirname $0)/compose.network.yml
echo "# This file is automatically generated by the $0 script" > $docker_network_file_path
echo "" >> $docker_network_file_path
echo "networks:" >> $docker_network_file_path
echo "  wpnetwork:" >> $docker_network_file_path
echo "    name: ${hash}_default" >> $docker_network_file_path
echo "    external: true" >> $docker_network_file_path
