name: CI
on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI (PHP ${{ matrix.env.php-version }} / WP ${{ matrix.env.wordpress-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        env: [
          { node-version: 20.x, php-version: 7.4, wordpress-version: 5.4 },
          { node-version: 20.x, php-version: 8.3, wordpress-version: 6.5.4 }
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.env.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.env.node-version }}
        cache: 'npm'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.env.php-version }}

    - name: Install phpcs
      run: composer global require squizlabs/php_codesniffer="3.9.2"
    - name: Install wpcs
      run: |
        composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
        composer global require --dev wp-coding-standards/wpcs:"3.1.0"

    - name: Setup Playwright cache
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-playwright-cache-${{ hashFiles('**/.storybook/main.js') }}
        restore-keys: ${{ runner.os }}-playwright-cache-
    - name: Install Playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - run: echo "PHP_VERSION=${{ matrix.env.php-version }}" >> $GITHUB_ENV
    - run: echo "WP_VERSION=${{ matrix.env.wordpress-version }}" >> $GITHUB_ENV

    - name: Install packages
      run: |
        source .bin/install-php-packages.sh &&
        npm ci

    - run: npm run lint:js
    - run: npm run format
    - run: npm run build
    - run: npm run env:start
    - run: npm run my-docker:start
    # wp-envの起動設定(--xdebug=)によってphpunitのテストは問題なく終了するが
    # カバレッジレポートが出力されない、という状況になるため、phpunitはcoverage出力オプションありをテスト実施項目とする。
    # ※ カバレッジレポートが出力されているかどうかのチェック処理は`postcoverage:phpunit`に記述。
    - run: npm run coverage:phpunit
    - run: npm run test:storybook


  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . \
          --file .devcontainer/Dockerfile.wp-plugin \
          --tag my/development:latest \
          --build-arg PHP_OLDEST_VERSION=7.4 \
          --build-arg PHP_LATEST_VERSION=8.3
