name: CI
on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
    - name: Install phpcs
      run: composer global require squizlabs/php_codesniffer="3.9.2"
    - name: Install wpcs
      run: |
        composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
        composer global require --dev wp-coding-standards/wpcs:"3.1.0"
    - run: npm ci
    - run: npm run env:start
    - run: npm run test
