name: CI
on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install phpcs
      run: composer global require squizlabs/php_codesniffer="3.9.2"
    - name: Install wpcs
      run: |
        composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
        composer global require --dev wp-coding-standards/wpcs:"3.1.0"

    - name: Setup Playwright cache
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-playwright-cache-${{ hashFiles('**/.storybook/main.js') }}
        restore-keys: ${{ runner.os }}-playwright-cache-
    - name: Install Playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - run: npm ci
    - run: npm run lint:js
    - run: npm run format
    - run: npm run build
    - run: npm run env:start
    - run: npm run my-docker:start
    # wp-envの起動設定(--xdebug=)によってphpunitのテストは問題なく終了するが
    # カバレッジレポートが出力されない、という状況になるため、phpunitはcoverage出力オプションありをテスト実施項目とする。
    # ※ カバレッジレポートが出力されているかどうかのチェック処理は`postcoverage:phpunit`に記述。
    - run: npm run coverage:phpunit
    - run: npm run test:storybook
