name: CI
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  node-version: 20.x

jobs:
  ci:
    name: CI (PHP ${{ matrix.env.php-version }} / WP ${{ matrix.env.wordpress-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        env: [
          { php-version: 7.4, wordpress-version: 5.4 },
          { php-version: 8.3, wordpress-version: 6.5.4 }
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.env.php-version }}

    - name: Install phpcs
      run: composer global require squizlabs/php_codesniffer="3.9.2"
    - name: Install wpcs
      run: |
        composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
        composer global require --dev wp-coding-standards/wpcs:"3.1.0"

    - run: echo "PHP_VERSION=${{ matrix.env.php-version }}" >> $GITHUB_ENV
    - run: echo "WP_VERSION=${{ matrix.env.wordpress-version }}" >> $GITHUB_ENV

    - name: Install PHP packages
      run: source .bin/install-php-packages.sh


    - name: Cache node_modules directory
      id: node_modules-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ env.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Clean install if node_modules cache is not hit
      run: |
        if [ "${{ steps.node_modules-cache.outputs.cache-hit }}" = "true" ]; then
          echo "Skip npm ci"
          npm run prepare
        else
          npm ci
        fi

    # Playwrightのインストールはnpm install後に実施する
    - name: Setup Playwright cache
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-playwright-cache-${{ hashFiles('**/package-lock.json') }}
        # restore-keys: ${{ runner.os }}-playwright-cache-
    - name: Install Playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps


    - name: Cache wp-env directory
      id: wp-env-cache
      uses: actions/cache@v4
      with:
        path: ~/wp-env
        key: ${{ runner.os }}-wp-env-PHP${{ matrix.env.php-version }}-WP${{ matrix.env.wordpress-version }}


    - run: npm run lint:js
    - run: npm run format
    - run: npm run build
    - run: npm run env:start
    - run: npm run my-docker:start
    - run: npm run test:storybook
    # wp-envの起動設定(--xdebug=)によってphpunitのテストは問題なく終了するが
    # カバレッジレポートが出力されない、という状況になるため、phpunitはcoverage出力オプションありをテスト実施項目とする。
    # ※ カバレッジレポートが出力されているかどうかのチェック処理は`postcoverage:phpunit`に記述。
    - run: npm run coverage:phpunit

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . \
          --file .devcontainer/Dockerfile.wp-plugin \
          --tag my/development:latest \
          --build-arg PHP_OLDEST_VERSION=7.4 \
          --build-arg PHP_LATEST_VERSION=8.3
